#!/usr/bin/env python3
"""
Generate ECDSA P-256 signing keypair for OTA firmware verification.

Outputs:
  - ota_signing_key.pem   (private key — keep secret!)
  - ota_public_key.h      (C header with embedded public key for firmware)

Usage:
    python3 generate_signing_key.py
    python3 generate_signing_key.py --output-dir keys/
"""

import argparse
import os
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import serialization


def generate_keypair(output_dir: str):
    os.makedirs(output_dir, exist_ok=True)

    # Generate ECDSA P-256 private key
    private_key = ec.generate_private_key(ec.SECP256R1())

    # Save private key as PEM
    pem_path = os.path.join(output_dir, "ota_signing_key.pem")
    pem_data = private_key.private_bytes(
        encoding=serialization.Encoding.PEM,
        format=serialization.PrivateFormat.PKCS8,
        encryption_algorithm=serialization.NoEncryption()
    )
    with open(pem_path, 'wb') as f:
        f.write(pem_data)
    os.chmod(pem_path, 0o600)
    print(f"Private key: {pem_path}")

    # Extract raw public key (uncompressed: 04 || x(32) || y(32) = 65 bytes)
    public_key = private_key.public_key()
    pub_bytes = public_key.public_bytes(
        encoding=serialization.Encoding.X962,
        format=serialization.PublicFormat.UncompressedPoint
    )
    assert len(pub_bytes) == 65 and pub_bytes[0] == 0x04

    # Write C header
    header_path = os.path.join(output_dir, "ota_public_key.h")
    with open(header_path, 'w') as f:
        f.write("#pragma once\n")
        f.write("#include <cstdint>\n\n")
        f.write("// ECDSA P-256 public key for OTA firmware verification\n")
        f.write("// Generated by tools/generate_signing_key.py\n")
        f.write("// WARNING: Do not commit the private key (ota_signing_key.pem)\n\n")
        f.write("static const uint8_t OTA_SIGNING_PUBLIC_KEY[65] = {\n")
        for i in range(0, len(pub_bytes), 12):
            chunk = pub_bytes[i:i+12]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {line},\n")
        f.write("};\n")
    print(f"Public key header: {header_path}")

    # Print key fingerprint (SHA-256 of public key)
    import hashlib
    fingerprint = hashlib.sha256(pub_bytes).hexdigest()[:16]
    print(f"Key fingerprint: {fingerprint}")
    print(f"\nCopy {header_path} to include/ in your project.")
    print(f"Keep {pem_path} SECRET — it signs your firmware.")


def generate_encryption_key(output_dir: str):
    """Generate a random AES-256 encryption key for firmware encryption."""
    os.makedirs(output_dir, exist_ok=True)
    key = os.urandom(32)

    # Save as hex file
    hex_path = os.path.join(output_dir, "ota_encryption_key.hex")
    with open(hex_path, 'w') as f:
        f.write(key.hex() + "\n")
    os.chmod(hex_path, 0o600)
    print(f"Encryption key (hex): {hex_path}")

    # Save as C header for embedding in firmware
    header_path = os.path.join(output_dir, "ota_encryption_key.h")
    with open(header_path, 'w') as f:
        f.write("#pragma once\n")
        f.write("#include <cstdint>\n\n")
        f.write("// AES-256 encryption key for OTA firmware decryption\n")
        f.write("// Generated by tools/generate_signing_key.py --encryption\n")
        f.write("// WARNING: Keep this key SECRET\n\n")
        f.write("static const uint8_t OTA_ENCRYPTION_KEY[32] = {\n")
        for i in range(0, 32, 12):
            chunk = key[i:i+12]
            line = ", ".join(f"0x{b:02x}" for b in chunk)
            f.write(f"    {line},\n")
        f.write("};\n")
    print(f"Encryption key header: {header_path}")
    print(f"\nCopy {header_path} to include/ and {hex_path} to keys/")
    print(f"Keep BOTH files SECRET — they decrypt your firmware.")


def main():
    parser = argparse.ArgumentParser(description='Generate OTA signing keypair')
    parser.add_argument('--output-dir', default='.', help='Output directory')
    parser.add_argument('--encryption', action='store_true',
                        help='Also generate AES-256 encryption key')
    args = parser.parse_args()
    generate_keypair(args.output_dir)
    if args.encryption:
        generate_encryption_key(args.output_dir)


if __name__ == '__main__':
    main()
